// Generated by CoffeeScript 1.10.0
(function() {
  var Connection, PassThrough, path, queryString, streamToBuffer, streamifier, url;

  url = require('url');

  queryString = require('query-string');

  path = require('path');

  PassThrough = require('stream').PassThrough;

  streamifier = require('streamifier');

  streamToBuffer = require('stream-to-buffer');

  Connection = (function() {
    function Connection(settings) {
      var key, query, ref, value;
      this.settings = settings;
      if (typeof this.settings === 'string') {
        this.settings = url.parse(this.settings);
      }
      if (this.settings.auth) {
        ref = this.settings.auth.split(':'), this.settings.user = ref[0], this.settings.password = ref[1];
        this.settings.username = this.settings.user;
      }
      if (this.settings.query) {
        query = queryString.parse(this.settings.query);
        for (key in query) {
          value = query[key];
          this.settings[key] = value;
        }
      }
    }

    Connection.prototype.connect = function(callback) {
      return callback(new Error('not implemented'));
    };

    Connection.prototype.close = function(callback) {
      return callback(new Error('not implemented'));
    };

    Connection.prototype.saveStream = function(stream, id, callback) {
      return callback(new Error('not implemented'));
    };

    Connection.prototype.saveData = function(data, id, callback) {
      var stream;
      stream = streamifier.createReadStream(data);
      return this.saveStream(stream, id, callback);
    };

    Connection.prototype.getStream = function(id, callback) {
      return callback(new Error('not implemented'));
    };

    Connection.prototype.getData = function(id, callback) {
      return this.getStream(id, (function(_this) {
        return function(err, stream) {
          if (err) {
            return deferred.reject(err);
          }
          return streamToBuffer(stream, function(err, data) {
            if (err) {
              return deferred.reject(err);
            }
            return deferred.resolve(data);
          });
        };
      })(this));
    };

    Connection.prototype.getPath = function(id) {
      if (id == null) {
        id = '';
      }
      return path.join(this.settings.pathname || '/', String(id));
    };

    return Connection;

  })();

  module.exports = Connection;

}).call(this);
