// Generated by CoffeeScript 1.10.0
(function() {
  var Connection, Promise, path, queryString, streamToBuffer, streamifier, url;

  url = require('url');

  queryString = require('query-string');

  path = require('path');

  streamifier = require('streamifier');

  streamToBuffer = require('stream-to-buffer');

  Promise = require('bluebird');

  Connection = (function() {
    function Connection(settings) {
      var key, query, ref, value;
      this.settings = settings;
      if (typeof this.settings === 'string') {
        this.settings = url.parse(this.settings);
      }
      if (this.settings.auth) {
        ref = this.settings.auth.split(':'), this.settings.user = ref[0], this.settings.password = ref[1];
        this.settings.username = this.settings.user;
      }
      if (this.settings.query) {
        query = queryString.parse(this.settings.query);
        for (key in query) {
          value = query[key];
          this.settings[key] = value;
        }
      }
    }

    Connection.prototype.connect = function() {
      return Promise.reject('not implemented');
    };

    Connection.prototype.close = function() {
      return Promise.reject('not implemented');
    };

    Connection.prototype.saveStream = function(stream, id) {
      return Promise.reject('not implemented');
    };

    Connection.prototype.saveData = function(data, id) {
      var stream;
      stream = streamifier.createReadStream(data);
      return this.saveStream(stream, id);
    };

    Connection.prototype.getStream = function(id) {
      return Promise.reject('not implemented');
    };

    Connection.prototype.getData = function(id) {
      return this.getStream(id).then((function(_this) {
        return function(stream) {
          return new Promise(function(resolve, reject) {
            return streamToBuffer(stream, function(err, data) {
              if (err) {
                return reject(err);
              }
              return resolve(data);
            });
          });
        };
      })(this));
    };

    Connection.prototype.getPath = function(id) {
      if (id == null) {
        id = '';
      }
      return path.join(this.settings.pathname || '/', String(id));
    };

    return Connection;

  })();

  module.exports = Connection;

}).call(this);
