// Generated by CoffeeScript 1.9.3
(function() {
  var FileManager, GenericPool, md5, queryString, streamBuffers, streamToBuffer, url;

  streamToBuffer = require('stream-to-buffer');

  streamBuffers = require('stream-buffers');

  url = require('url');

  queryString = require('query-string');

  md5 = require('md5');

  GenericPool = require('generic-pool');

  FileManager = (function() {
    function FileManager(settings) {
      var key, query, ref, ref1, value;
      this.settings = settings;
      if (typeof this.settings === 'string') {
        this.settings = url.parse(this.settings);
      }
      if (this.settings.auth) {
        ref = this.settings.auth.split(':'), this.settings.user = ref[0], this.settings.password = ref[1];
        this.settings.username = this.settings.user;
      }
      if (this.settings.query) {
        query = queryString.parse(this.settings.query);
        for (key in query) {
          value = query[key];
          this.settings[key] = value;
        }
      }
      this.type = (ref1 = this.settings.protocol) != null ? ref1.replace(':', '') : void 0;
      this.pool = GenericPool.Pool({
        name: this.type,
        create: (function(_this) {
          return function(callback) {
            var Connection, connection;
            Connection = require(__dirname + "/connections/" + _this.type + ".js");
            connection = new Connection(_this.settings);
            return connection.connect(function(err) {
              if (err) {
                callback(err);
              }
              return callback(null, connection);
            });
          };
        })(this),
        destroy: (function(_this) {
          return function(connection) {
            return connection.close(function() {});
          };
        })(this),
        max: this.settings.maxConnections || 1,
        idleTimeoutMillis: 1000 * (this.settings.ttl || 60)
      });
    }

    FileManager.prototype.saveStream = function(stream, id, callback) {
      if (typeof id === 'function') {
        callback = id;
        id = this.getNewId();
      }
      callback = callback || function() {};
      return this.pool.acquire((function(_this) {
        return function(err, connection) {
          return connection.saveStream(stream, id, function(err, info) {
            _this.pool.release(connection);
            return callback(err, info);
          });
        };
      })(this));
    };

    FileManager.prototype.saveData = function(data, id, callback) {
      var streamBuffer;
      streamBuffer = new streamBuffers.ReadableStreamBuffer();
      streamBuffer.put(data);
      this.saveStream(streamBuffer, String(id), callback);
      return streamBuffer.destroySoon();
    };

    FileManager.prototype.getStream = function(id, callback) {
      callback = callback || function() {};
      return this.pool.acquire((function(_this) {
        return function(err, connection) {
          return connection.getStream(id, function(err, stream) {
            _this.pool.release(connection);
            if (err) {
              return callback(err);
            }
            return callback(null, stream);
          });
        };
      })(this));
    };

    FileManager.prototype.getData = function(id, callback) {
      callback = callback || function() {};
      return this.getStream(String(id), (function(_this) {
        return function(err, stream) {
          if (err) {
            return callback(err);
          }
          return streamToBuffer(stream, callback);
        };
      })(this));
    };

    FileManager.prototype.getNewId = function() {
      return md5((Math.random() * 100000) + Date.now());
    };

    FileManager.prototype.remove = function(id, callback) {
      return this.pool.acquire((function(_this) {
        return function(err, connection) {
          return connection.remove(String(id), function(err) {
            _this.pool.release(connection);
            return callback(err);
          });
        };
      })(this));
    };

    return FileManager;

  })();

  module.exports = FileManager;

}).call(this);
