// Generated by CoffeeScript 1.10.0
(function() {
  var Connection, FileConnection, Lock, fs, lock, path,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  fs = require("fs");

  path = require('path');

  Lock = require('lock');

  Connection = require('../Connection');

  lock = Lock();

  FileConnection = (function(superClass) {
    extend(FileConnection, superClass);

    function FileConnection() {
      return FileConnection.__super__.constructor.apply(this, arguments);
    }

    FileConnection.prototype.connect = function(callback) {
      if (!this.settings.path) {
        return callback(new Error("settings.path must be specified"));
      } else {
        return callback();
      }
    };

    FileConnection.prototype.close = function(callback) {
      return callback();
    };

    FileConnection.prototype.ensureDirectory = function(id, callback) {
      var dir, filename, rootDir;
      filename = this.getPath(id);
      rootDir = this.getPath();
      dir = path.dirname(filename);
      if (dir === rootDir) {
        return callback();
      }
      return lock(dir, (function(_this) {
        return function(release) {
          callback = release(callback);
          return fs.exists(dir, function(exists) {
            if (exists) {
              return callback();
            }
            return fs.mkdir(dir, callback);
          });
        };
      })(this));
    };

    FileConnection.prototype.saveStream = function(stream, id, callback) {
      return this.ensureDirectory(id, (function(_this) {
        return function(err) {
          if (err) {
            return callback(err);
          }
          return _this._saveStream(stream, id, callback);
        };
      })(this));
    };

    FileConnection.prototype._saveStream = function(stream, id, callback) {
      var err, error, writeStream;
      writeStream = void 0;
      try {
        writeStream = fs.createWriteStream(this.getPath(id));
      } catch (error) {
        err = error;
        callback(err);
      }
      stream.on("end", function() {
        return callback(null, {
          id: id
        });
      });
      stream.on("error", function(err) {
        return callback(err);
      });
      stream.pipe(writeStream);
    };

    FileConnection.prototype.getStream = function(id, callback) {
      var filename;
      filename = this.getPath(id);
      return fs.exists(filename, (function(_this) {
        return function(exists) {
          if (!exists) {
            return callback(new Error('record ' + id + ' doesn\'t exists'));
          }
          return callback(null, fs.createReadStream(filename));
        };
      })(this));
    };

    FileConnection.prototype.remove = function(id, callback) {
      fs.unlink(this.getPath(id), callback);
    };

    return FileConnection;

  })(Connection);

  module.exports = FileConnection;

}).call(this);
